### ISSUE TITLE
Can't get anything to work

### ISSUE THREAD

**Issue by jpgagnon73** [ETCLabs/lighthack#4]
So, I've wired it all up, several times.  Loaded the sketch with OSC library several times, no errors.  I only get 1 line of squares on the display and not one ounce of control.  I am running an Uno.  is v3 vital to this project working?  Is there something missing in the code??
Thanks
JP

**Comment by samkearney** [comment]
:confused: 

We have tested the code as it exists here with Nomad PC and several consoles. Note that there is no support for Nomad Mac yet. Some things to try:

- Troubleshooting section at the end of the assembly instructions document
- Watch the Eos logs ([Tab] & 99) when you connect the Arduino to the console. You should see messages scroll by that look similar to:
  - OSC USB Device Connected (Handshake Required)
  - OSC USB Device Handshake Initiated [ETCOSC?]
  - OSC USB Device Handshake Complete [OK]

  This will verify that basic OSC USB connectivity is working between the device and the Eos software. Then you'll know that it's a hardware/wiring issue.

 I took a look at the differences between Uno original, R2 and R3 [here](http://startingelectronics.org/articles/arduino/uno-r3-r2-differences/); We tested on an R3, but I see nothing that would make the code function differently on an R2 or earlier.

**Comment by jpgagnon73** [comment]
Ok, well I've been doing it on a mac only at this point.  i will try on my dedicated nomad PC at home.  one question, does the display show anything until it connects to EOS?

**Comment by jpgagnon73** [comment]
And I just verified that the UNO i'm using is an R3.  Sometimes I need to open my eyes more.

**Comment by samkearney** [comment]
Yes, if there is no Eos connection there should be a default display which looks like:

```
Pan:  0.000
Tilt: 0.000
```

If you are getting a line of squares, I strongly suspect a wiring issue. Double check the wiring and especially the solder joints (cold solder joints tripped us up once while we were testing).

**Comment by jpgagnon73** [comment]
yeah, I just get squares.  I am going to resolder the whole thing.  Curious, can the display be tweaked to show
              PAN          TILT
            0.000         0.000

I think this would make more sense in terms of the layout of the encoders.  Also, any reason we could use the encoder push down function to toggle the fine/coarse?

**Comment by samkearney** [comment]
The beauty of this being a DIY project is that you can make it do whatever you want! Our code is just a guideline / jumping off point. Your changes are totally doable with just a few tweaks to the code (the encoder push down change might require some new wiring too).

**Comment by jpgagnon73** [comment]
I am hoping it will be easy to change the text.  i would love to make this a 3 encoder box, so it will be more useful to mod to do other ML attributes down the road.  Thanks for your hard work on this.  Hopefully I can get it all working once I re-solder it all.

**Comment by samkearney** [comment]
Glad to help, and good luck! I'm told there will soon be a forum dedicated to this project on the ETC Community, so when that goes live I encourage you to post your modifications so other DIYers can take note!
