### ISSUE TITLE
Simpler LCD Screen

### ISSUE THREAD

**Issue by jpgagnon73** [ETCLabs/lighthack#6]
I would love to try and use the 16x2 display from this link here:  http://wiki.sunfounder.cc/index.php?title=I²C_LCD1602#Step_3:_Copy_the_code

This uses Pins A4 &A5 for all data to the lcd instead of D2-5 +D11+12.  Much simpler build.  But I'm having problem getting it to work in the sketch.  Any help would be greatly appreciated.  

I know I would have to change the Encoders to use Pins A0+A1 and A2+A3  (not sure why A2 and A5 were originally used in the sketch since nothing is connected to them physically.)

JP

**Comment by samkearney** [comment]
Looks like you will need to download and include the LiquidCrystal_I2C library (seems to be a separate library from the LiquidCrystal one we use)

> (not sure why A2 and A5 were originally used in the sketch since nothing is connected to them physically.)

I think it's cruft that was originally intended to read the encoder's pushbutton, which we ended up not using in our example. I'll rip that out in the next update. For a quick fix, you can probably simply move the second encoder to pins A2+A3, and change lines 452 and 453:
```Arduino
initEncoder(&panWheel, A0, A1, 9, PAN_DIR);
initEncoder(&tiltWheel, A2, A3, 10, TILT_DIR);
```
9 and 10 are just two unused pins in the example. Then follow their instructions for including the LiquidCrystal_I2C library and copy their example code for initting the LCD (disclaimer: I have not tested this)

**Comment by jpgagnon73** [comment]
When putting it into the sketch I kept getting errors like VOID already defined or other things.  I got it to work on it's own from the sample sketch they provided.  Something I'm missing I guess and not sure where to look.

**Comment by jpgagnon73** [comment]
OK, found my issues.  Mostly it was where I was putting the Init LCD Code.  Found the correct placement where the original was.  And thanks for the InitEncoder change.  That workaround should work great.  This also works with the 20x4 version of this display as well, just need to setup the display for those parameters.  Now, what to do with the extra screen real estate.
