### ISSUE TITLE
xp machines not functioning

### ISSUE THREAD

**Issue by Druuka** [ETCLabs/lighthack#7]
Per a discussion with Matt Pumplin on the ETC forums I think we should include this info on the readme.
I should also note that OSC over USB is not implemented / supported for Windows XP consoles and computers.

**Comment by jpgagnon73** [comment]
Will XP machines ever be supported for USB/OSC?  It's a real shame to all the legacy consoles out there to not have this functionality, especially the Element owners out there.

**Comment by samkearney** [comment]
@MizPlusPlus can you weigh in on prospects for future XP support, before I update the README?

**Comment by samkearney** [comment]
I've been told Windows XP support is not planned for this project. I'll update the README shortly to reflect that.

Don't forget that [Element consoles are eligible for upgrade to Windows 7](http://www.etcconnect.com/Support/Articles/Windows-7-Upgrade-Eligibility.aspx), which will enable them to work with these devices.
